language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t shasankasekhar/react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true shasankasekhar/react-app npm run test
  # earlier it was - docker run shasankasekhar/react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-199578526624"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  